### ISSUE TITLE
Install fails.

### ISSUE THREAD

**Issue by asyahana-icsp** [YoshinoriN/docker-redmine-orchestration#62]
お世話になっております。

当docker-redmine-orchestrationをDLし、ご記載の手順で実行したところ、
redmine_download_shの実行時に、
`md5sum: redmine-4.0.4.tar.gz: そのようなファイルやディレクトリはありません`
`./redmine_download_sh: 17行: [: 35a～: 単項演算子が予期されます]`
`[WARN] Doesn't match the check sum.`
`[INFO] Finish.`

と表示され、インストールができません。
恐らくチェックサムとの相違があるためかと思われますので、お手数ですがご確認の程お願い申し上げます。

また、もし差し支えなければ、最新版Redmine（Ver.4.1.1）に対応頂きますと幸いです。

どうぞよろしくお願い致します。

**Comment by yoshinorin** [comment]
@asyahana 
返信遅くなりました。すみません。
RedmineのURLが`http`から`https`に変わっていたことが原因でした（エラーメッセージが適切でなく申し訳ありません）

> もし差し支えなければ、最新版Redmine（Ver.4.1.1）に対応頂きますと幸いです。

[4.1.1対応したものをリリース](https://github.com/YoshinoriN/docker-redmine-orchestration/releases/tag/v4.1.1)しました。

`4.1.1`のバージョンアップにあわせて主に各種ライブラリやミドルウェア（nginx, MariaDB）のバージョンアップなどを行っています。詳細はリリースノートをご確認ください。

もし、MariDB`10.4`以前を使用していた場合はデータベースのアップグレードが必要になります。その場合は下記のどちらかでご対応ください。

* バックアップ取得の上でMariaDBのコンテナに入り `mysql_upgrade`を実施する
* [MariaDBのDockerfile](https://github.com/YoshinoriN/docker-redmine-orchestration/blob/6f3826255a0f75dceb7b162179fd76ce4c9a6e19/mariadb/Dockerfile#L1)のバージョンを現在使用しているバージョンにあわせたうえで`docker-compose up`する

---

もし、`4.0.4`のバージョンが必要な場合は下記の`Assets`からダウンロードするか、もしくは`git clone`した後にコミット dbf3518d843074f828669df489e30c981cf3f99c をチェックアウトして利用してください。

* [v4.0.4-2](https://github.com/YoshinoriN/docker-redmine-orchestration/releases/tag/v4.0.4-2)

**Comment by asyahana-icsp** [comment]
お返事ありがとうございます。
リリースされたgitリポジトリをDLし、実行したところインストールされました。
また、Redmineも表示されました。
ご対応ありがとうございます。

当チケットはCloseとさせて頂きます。
