### ISSUE TITLE
apk add command in Dockerfile fails

### ISSUE THREAD

**Issue by rafaelteb** [YoshinoriN/docker-redmine-orchestration#63]
Hi there!
Tried your setup.
So the apk command in the dockerfile is not working anymore. This command:
````
&& apk add --no-cache mysql-client tzdata mariadb-dev=10.4.13-r0 linux-headers=5.4.5-r1 imagemagick-dev=7.0.10.12-r0 \
````

Got following error from your Dockerfile when trying to build it:

````
ERROR: unable to select packages:
  linux-headers-5.7.8-r0:
    breaks: world[linux-headers=5.4.5-r1]
    satisfies: libffi-dev-3.3-r2[linux-headers]
  imagemagick-dev-7.0.10.57-r0:
    breaks: world[imagemagick-dev=7.0.10.12-r0]
  mariadb-dev-10.5.8-r0:
    breaks: world[mariadb-dev=10.4.13-r0]

````

I tried it myself with the official redmine images first. But there I got some SSL issues while using rake to get my emials from imap and could not find a solution. Maybe your setup can help me fix that!

**Comment by yoshinorin** [comment]
@rafaelteb 
Sorry, so late reply.

I fixed it and release new version. It's supports Redmine `4.2.0`.

> https://github.com/yoshinorin/docker-redmine-orchestration/releases/tag/v4.2.0

Thank you :)
